### ISSUE TITLE
creating scoreboard fails

### ISSUE THREAD

**Issue by konrad2002** [konrad2002/ORAV-Plugin#2]
on startup plugin does not enable because of following stacktrace:

```[04:17:34 ERROR]: Error occurred while enabling orav v1.0 (Is it up to date?)
java.lang.IllegalArgumentException: An objective of name 'Sidebar' already exists
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[commons-lang-2.6.jar:2.6]
	at org.bukkit.craftbukkit.v1_19_R1.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:55) ~[paper-1.19.2.jar:git-Paper-189]
	at org.bukkit.craftbukkit.v1_19_R1.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:84) ~[paper-1.19.2.jar:git-Paper-189]
	at org.bukkit.craftbukkit.v1_19_R1.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:79) ~[paper-1.19.2.jar:git-Paper-189]
	at org.bukkit.craftbukkit.v1_19_R1.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:20) ~[paper-1.19.2.jar:git-Paper-189]
	at de.logilutions.orav.scoreboard.ScoreboardHandler.registerObjectives(ScoreboardHandler.java:47) ~[orav-2.0.0-20221002.020301-3.jar:?]
	at de.logilutions.orav.scoreboard.ScoreboardHandler.<init>(ScoreboardHandler.java:35) ~[orav-2.0.0-20221002.020301-3.jar:?]
	at de.logilutions.orav.OravPlugin.onEnable(OravPlugin.java:93) ~[orav-2.0.0-20221002.020301-3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-189]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-189]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-189]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-189]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-189]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-189]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-189]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by konrad2002** [comment]
fixed very dirty, but enables now
